export const productsMockData: ProductsResponse = {
  products: [
    {
      id: 0,
      title: 'Наушники',
      list: [
        {
          id: 0,
          img: '/assets/images/products/headphones/1.png',
          title: 'Apple BYZ S852I',
          price: 2927,
          rate: 4.7,
        },
        {
          id: 1,
          img: '/assets/images/products/headphones/2.png',
          title: 'Apple EarPods',
          price: 2327,
          rate: 4.5,
        },
        {
          id: 2,
          img: '/assets/images/products/headphones/3.png',
          title: 'Apple DJK Lobj',
          price: 5427,
          rate: 3.6,
        },
        {
          id: 3,
          img: '/assets/images/products/headphones/1.png',
          title: 'Apple BYZ S852I',
          price: 2927,
          rate: 4.7,
        },
        {
          id: 4,
          img: '/assets/images/products/headphones/2.png',
          title: 'Apple EarPods',
          price: 2327,
          rate: 4.5,
        },
        {
          id: 5,
          img: '/assets/images/products/headphones/3.png',
          title: 'Apple DJK Lobj',
          price: 5427,
          rate: 3.6,
        },
      ],
    },
    {
      id: 1,
      title: 'Беспроводные наушники',
      list: [
        {
          id: 6,
          img: '/assets/images/products/wireless-headphones/1.png',
          title: 'Apple BYZ S852I',
          price: 9527,
          rate: 4.4,
        },
        {
          id: 7,
          img: '/assets/images/products/wireless-headphones/2.png',
          title: 'Apple EarPods',
          price: 6527,
          rate: 4.9,
        },
        {
          id: 8,
          img: '/assets/images/products/wireless-headphones/3.png',
          title: 'Apple DJK Lobj',
          price: 7527,
          rate: 4.7,
        },
        {
          id: 9,
          img: '/assets/images/products/wireless-headphones/1.png',
          title: 'Apple BYZ S852I',
          price: 9527,
          rate: 4.4,
        },
        {
          id: 10,
          img: '/assets/images/products/wireless-headphones/2.png',
          title: 'Apple EarPods',
          price: 6527,
          rate: 4.9,
        },
        {
          id: 11,
          img: '/assets/images/products/wireless-headphones/3.png',
          title: 'Apple DJK Lobj',
          price: 7527,
          rate: 4.7,
        },
      ],
    },
  ],
};
